development:
  adapter: postgresql
  encoding: unicode
  database: fancy_coffee_table_dev
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: postgresql
  encoding: unicode
  database: fancy_coffee_table_test
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8